# Generated by Django 4.0.3 on 2022-04-07 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminHSI', '0005_alter_soal_option_four_alter_soal_option_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peserta_NIP', models.CharField(max_length=20)),
                ('Peserta_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Soal_Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Choice', models.CharField(max_length=1)),
                ('Status', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('Peserta_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PesertaHSI.peserta')),
                ('Soal_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminHSI.soal')),
            ],
        ),
    ]
