# Generated by Django 4.0.3 on 2022-04-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PesertaHSI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal_peserta',
            name='Peserta_ID',
        ),
        migrations.AlterField(
            model_name='soal_peserta',
            name='Soal_ID',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Peserta',
        ),
    ]
