# Generated by Django 4.0.3 on 2022-04-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PesertaHSI', '0002_remove_soal_peserta_peserta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soal_peserta',
            name='date_posted',
        ),
        migrations.AddField(
            model_name='soal_peserta',
            name='Paket_Soal_ID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
