# Generated by Django 4.0.3 on 2022-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PesertaHSI', '0003_remove_soal_peserta_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal_peserta',
            name='Nilai',
            field=models.IntegerField(null=True),
        ),
    ]
