# Generated by Django 4.0.3 on 2022-04-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminHSI', '0005_alter_soal_option_four_alter_soal_option_one_and_more'),
        ('PesertaHSI', '0004_soal_peserta_nilai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal_peserta',
            name='Soal_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soal', to='adminHSI.soal'),
        ),
    ]
