# Generated by Django 4.0.3 on 2022-04-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PesertaHSI', '0005_alter_soal_peserta_soal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal_peserta',
            name='Soal_ID',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
