# Generated by Django 4.0.4 on 2022-04-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PesertaHSI', '0008_soal_peserta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal_peserta',
            name='Soal_ID',
            field=models.TextField(null=True),
        ),
    ]
