# Generated by Django 4.0.3 on 2022-03-29 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminHSI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soal',
            name='option_five',
            field=models.TextField(default=django.utils.timezone.now, verbose_name=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soal',
            name='option_four',
            field=models.TextField(default=django.utils.timezone.now, verbose_name=0),
            preserve_default=False,
        ),
    ]
