# Generated by Django 4.0.3 on 2022-03-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHSI', '0002_soal_option_five_soal_option_four'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='option_five',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='soal',
            name='option_four',
            field=models.CharField(max_length=30),
        ),
    ]
