# Generated by Django 4.0.3 on 2022-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminHSI', '0004_remove_soal_option_five'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soal',
            name='option_four',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soal',
            name='option_one',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soal',
            name='option_three',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='soal',
            name='option_two',
            field=models.CharField(max_length=200),
        ),
    ]
