# Generated by Django 4.0.3 on 2022-04-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminHSI', '0005_alter_soal_option_four_alter_soal_option_one_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soal',
            options={'verbose_name_plural': 'Soals'},
        ),
    ]
